# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    - CONFIG=osx_r_base3.4.1target_platformosx-64
    - CONFIG=osx_r_base3.5.1target_platformosx-64

  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "jbRs2mBHkBWtHqsgi2nBrR3JnmK6tumFPzYmgtnqrQmaRHW1pMc8M4H00xkHc1mLJioZotS8RI9pgx/wny6+w86vr8Grh6rPYdUiYFRpqeqaDFEiiix1DUPDB7DYxlXhZLblMyvp2Jv9cLU/aZI2zrUOgwi0KhjDKpopUm0CVa+yMRMdkE/+lj7f6iNSB1JnPscqkiEDWZwFoVfxfRkwYVXuO5C/koWdtvNmvKecdj1mIJ9kS5Ecr4t57BmrVcpDdvh4YSgbBIattxwXOXI9ioj7WqtilP/HU7K9TVHsY0MeUtA9QQCIXAs6dUHkvzWMaK//oZQqqUlA5Oh9N2vJrpj6KXvJiSH1YwkFyyR2iXII1hiWGimfT/6BQxRlRKdPNT4RKU5n6Kr5sbD9dCOPH4c+OfhuPvC5/1z5XTFxI1fxKJx/gpoqvTFPn9uEEl5oYk0oRVcomAPvNDxKOLHMPwPez+FRTMEz/rQYx9mqRvR6d+pjs/DBgG+xmjwJOGWx4KHK1b5XDgeNQ5CPBEPah5NjJWt5soRtdDlI8JhBNwCn4477RRZmWij9GGHkSXoMLs/zynaLpRKB2z6yi2KcA9sFziAzfJaLMWMqbCU8VyKVYz5LfHuWWadb76rEuhTkI2QLzOpypQQxfkOmJWY1TlrviFujmHBJjSxy0ZH6aG4="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-ci-setup-feedstock/branch2.0/recipe/conda_forge_ci_setup/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root

      conda install --yes --quiet conda-forge::conda-forge-ci-setup=2
      setup_conda_rc ./ ./recipe ./.ci_support/${CONFIG}.yaml

      source run_conda_forge_build_setup

    # compiler cleanup
    - |
      mangle_compiler ./ ./recipe ./.ci_support/${CONFIG}.yaml

script:
  # generate the build number clobber
  - make_build_number ./ ./recipe ./.ci_support/${CONFIG}.yaml
  - conda build ./recipe -m ./.ci_support/${CONFIG}.yaml --clobber-file ./.ci_support/clobber_${CONFIG}.yaml
  - upload_package ./ ./recipe ./.ci_support/${CONFIG}.yaml
