travis:
  secure:
    BINSTAR_TOKEN: xqSrXm5aly09y0T9IYeBOUpBBi3jiB48TPzqkrxm3kCclB0WZMEZw+cy2x88EX5HXjFoG2fNdhuT+FQgJh+9FYPWcBYPTntzMVwTGWex6q1n2s1TkwOq7JcuECfsafMqYhVNTr7HOCeRVltV2CjXO4tRQybl7GUdIYw4frA+BZLHXddfTLDWttBnOzgqt5IXBg0SkoHDt3IU0dj2D2KH6+bZYhxdhkDZceBysTsXBfEUz0auuSnz7mjpGlBAVEb6lk1TIc3tDFQytfmmix62+unkZxQ0IzZS81xkc8QDJt8Gu0RJhiPdskHuI+xmwUMmBLK36UJwQWimV63ZEmRk95F9mgfQJ+VuaYjzmW//9omhuzvaDBGJ/1KS27pU2eA60PAi5LaHL2IYMKH7T+vnQ8TAbGzI1YaiVgoiDrq0nAY1XIlJmjpeI4g5nnaDlbvTdNmUv7nFRvvurRWDb29InWfd+s1YieCoOObuG5bdsEi+cf1WOQofT+9oieG4kws7EyT/6OojPZfOF2sof9qiowgVGZ6IL3pXW7QPvJ00BmcAP+0oZWyCHVlziWsqm3mcFCWfxbnV7oSM9SuUhf5XPgGYEFpxN76GqUt1agbvbXpNN8imFUe4lsQN5/3Vc19KcXM6RJagSlDX7N32yLcCpRxrVTqOyXVqFzoVUcuCL1Y=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
