travis:
  secure:
    BINSTAR_TOKEN: GZ9WlFdxvIcCxSZmRmy/ozxwLyrsSoQRvhXPp9URvjUzEiXm1DSGjHlRSLdzV+l95ytxUTByOh7HH16ljrU5n0cOm8BvG3L+YSYggSIObq0ewIzhvwi6fei/f6wmwboThESNZQiI59TBP37gzOxcZv5i6NXDf9pvc/Z6lBpIHOjKguVssiPf74OhejNPvaRhCUKj7gMglG4nhgq0R07+n6XqUFKhmJcZ7vkcDIu/a24tRweM3ZdD43vPT6H6DK8z4bFDMv9orHrzp3sg4xduaddwgmc0ChjXIbcp1vESnnDWX5jENC2bArhwYILOzBiLv0J/+1FSaODb4JdJFopvy3gLBJywITzVrgx8doyVSRj0jnEZXlpJjFmCfjioqfn3OR3W+sFYl8Bery1RC9ok+9NLJHoqpxMwJ7aVtwiOHaHMVSivHo1zyazA7FkIvjAvXgEdnxYKlKzcVOypQtt083/+tjvVwO70eLE5bqww2tMjBImCK5jOMMnKu35Yz2i301QyzBj6TiRzV4xPVZk1pt0cjoIUmEHSmtmO2Sh+5OeNaX6PBmn8ohJXXY+Veh4IQKbdY/AsN0NEDeGRm+CxTczuPphYNxPpXKgslT3qhkwBeK9f9mgUd1MU0EcmDhVlJidg2YPo3yhuo91NX3jfvqc/RUIfpaEwlDadqWAlm1c=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
