appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: jbRs2mBHkBWtHqsgi2nBrR3JnmK6tumFPzYmgtnqrQmaRHW1pMc8M4H00xkHc1mLJioZotS8RI9pgx/wny6+w86vr8Grh6rPYdUiYFRpqeqaDFEiiix1DUPDB7DYxlXhZLblMyvp2Jv9cLU/aZI2zrUOgwi0KhjDKpopUm0CVa+yMRMdkE/+lj7f6iNSB1JnPscqkiEDWZwFoVfxfRkwYVXuO5C/koWdtvNmvKecdj1mIJ9kS5Ecr4t57BmrVcpDdvh4YSgbBIattxwXOXI9ioj7WqtilP/HU7K9TVHsY0MeUtA9QQCIXAs6dUHkvzWMaK//oZQqqUlA5Oh9N2vJrpj6KXvJiSH1YwkFyyR2iXII1hiWGimfT/6BQxRlRKdPNT4RKU5n6Kr5sbD9dCOPH4c+OfhuPvC5/1z5XTFxI1fxKJx/gpoqvTFPn9uEEl5oYk0oRVcomAPvNDxKOLHMPwPez+FRTMEz/rQYx9mqRvR6d+pjs/DBgG+xmjwJOGWx4KHK1b5XDgeNQ5CPBEPah5NjJWt5soRtdDlI8JhBNwCn4477RRZmWij9GGHkSXoMLs/zynaLpRKB2z6yi2KcA9sFziAzfJaLMWMqbCU8VyKVYz5LfHuWWadb76rEuhTkI2QLzOpypQQxfkOmJWY1TlrviFujmHBJjSxy0ZH6aG4=}
