travis:
  secure:
    BINSTAR_TOKEN: GziM1Bb2H9GoQWbAAykr8gBgof8CAfohBOfC7xQJsbdNVR4y6H/5AjY+Ncoua8Pglq5E3FaKu3coSU5LXiTdLQJBoYAQUNSk1bUHowu7WP7bHp1blh9uEGoR7AmlND/eF3NVb+WzG1oQGkLC3w1EQb/Ay9zWEO7t1YRuJ9UHrpcHZpdBD2+2OVDKGvG3TDGSgH3NlsgaDTvaPJTzC6xYBEvS6+SUPINkC1oTBYmXAqvjpkf1Zf1MZX67L1CVy1fzpvpnzuYOmKyRal9XO/Ie/LtxauEwxHQa9ekPM7+Kv4YgIzsFGIEIEKN/niwsTEHsEniFfjLhEqnqgSbi3J06GCDCQ8CzL1CWt+LW+GFhubmFrRg+Oku6zpF1KiX5oZm7+M9dYpORvvz/P23DezLCUgUWaJLy+Q9x9PVCjyOeYUYxS8niNigWH56IYjYyNsRGrjnMAQapUgZfikYKD5qAxVto47IwsczmQgnfIkxlTBFShHTk5pcX2TziKcn4kw8Xo2kS7Psys4EAKq+ilezjJQzNVH9vdw3nXlTHcvCYsC8OtNLrPzgORo4VxkykF+xDURWyxvB1EfG9b7TYnEl0/YvazPg+mNbZ5eXDzIcDTl9EASYVBbKeSx5/XBVeYjc/Wc2C8i0/iBoaLZUFrjwl+tZQ4913snMO9cFw3GQAcfI=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
